export PYTHONPATH=/home/anmolg/work/monai/lisa/nemo_shreyas_fork/NeMo-fork:$PYTHONPATH
torchrun --nproc_per_node=1 /home/anmolg/work/monai/lisa/nemo_shreyas_fork/NeMo-fork/examples/multimodal/multimodal_llm/lisa/lisa_evaluation.py \
tensor_model_parallel_size=1 \
pipeline_model_parallel_size=1 \
neva_model_file=/home/anmolg/work/monai/lisa/ckpts/lisa_ckpt/lisa_to_nemo_fp32/lisa_7b_v1/lisa_7B_v1.nemo \
trainer.devices=1 \
trainer.precision=32 \
prompt_file=/home/anmolg/work/monai/lisa/ckpts/lisa_ckpt/lisa_to_nemo_fp32/lisa_7b_v1/lisa_inference_demo/input.jsonl \
inference.media_base_path=/home/anmolg/work/monai/lisa/ckpts/lisa_ckpt/lisa_to_nemo_fp32/lisa_7b_v1/lisa_inference_demo/images \
output_file=/home/anmolg/work/monai/lisa/ckpts/lisa_ckpt/lisa_to_nemo_fp32/lisa_7b_v1/lisa_inference_demo/output/output.jsonl \
output_seg_image_file=/home/anmolg/work/monai/lisa/ckpts/lisa_ckpt/lisa_to_nemo_fp32/lisa_7b_v1/lisa_inference_demo/output/seg_result.jpg \
output_mask_image_file=/home/anmolg/work/monai/lisa/ckpts/lisa_ckpt/lisa_to_nemo_fp32/lisa_7b_v1/lisa_inference_demo/output/mask_result.jpg \
inference.temperature=0.2 \
inference.top_k=0 \
inference.top_p=0.9 \
inference.greedy=False \
inference.add_BOS=False \
inference.all_probs=False \
inference.repetition_penalty=1.2 \
inference.insert_media_token=left \
inference.tokens_to_generate=256 \
quantization.algorithm=awq \
quantization.enable=False
